### ISSUE TITLE
VolumeExpansion ONLINE/OFFLINE capability is not checked

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-resizer#62]
When a CSI driver reports PluginCapability_VolumeExpansion_OFFLINE only, external-resizer still calls ControllerExpandVolume when the PVC is used by a Pod.

Instead, the extenal-resizer should check VolumeExpansion plugin capability and only invoke ControllerExpandVolume when PluginCapability_VolumeExpansion_ONLINE is supported by the CSI driver.

**Comment by xing-yang** [comment]
assign @gnufied

**Comment by gnufied** [comment]
This issue is still in our radar. The reason, we have been hesitant in fixing this is because - any checks we perform in external-resizer to determine if volume is in-use before making controller-expansion call, will be racy. 

We can either perform a best-case check in external-resizer but since that will be still  subject to races, the plugins must be able to handle such expansion calls and return grpc errors. So volume expansion requests will still be retried, the only difference will be which component returns errors. If external-resizer checks for volume in-use before calling `ControllerExpandVolume` it will return errors, but if plugin does receive the call (even if volume is in-use), it is the one that will have to return an error.

**Comment by xing-yang** [comment]
That sounds good.  If external-resizer can check if volume is in-use before calling ControllerExpandVolume, that should cover most cases.  In the corner case if the call still reaches the plugin, the plugin will return an error.

**Comment by gnufied** [comment]
Summary of discussion on April 2nd 2020:

We discussed the option of doing a best case check but agreed that - it could worsen the problem where a driver author might falsely (after limited testing) assume that `ControllerExpandVolume` will not be called if volume is in-use.  In the end - driver does need to handle when this happens and return following error as per CSI spec:

```
| Volume in use | 9 FAILED_PRECONDITION | Indicates that the volume corresponding to the 
specified `volume_id` could not be expanded because it is currently published on a node but the 
plugin does not have ONLINE expansion capability. | Caller SHOULD ensure that volume is not 
published and retry with exponential back off. |
```

Elsewhere in CSI spec though - SHALL and MUST word is used to describe OFFLINE expansion. I have filed https://github.com/container-storage-interface/spec/issues/423 to discuss this in CSI community meeting.

**Comment by gnufied** [comment]
Another thing is - even checking resizing condition while doing mount or attach suffers from race conditions that are mentioned in - https://github.com/kubernetes-csi/external-resizer/issues/62#issuecomment-582004580  so aren't entirely fullproof.

**Comment by xing-yang** [comment]
This is fixed.

**Comment by niladrih** [comment]
I think, this behaviour is still present as of kubernetes v1.27.3.
